name: CI Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21
        - name: Build
          run: go build -o HentaiAtHomeExporter
        - name: Archive
          uses: actions/upload-artifact@v2
          with:
            name: HentaiAtHomeExporter
            path: HentaiAtHomeExporter
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: HentaiAtHomeExporter
          if: startsWith(github.ref, 'refs/tags/')

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

